services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
#      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - localnet

  face_recognition:
    image: alejandroqo/facenet-service
    environment:
      - CAMERA_URL=rtsp://acecom:1964@192.168.1.19:8080/h264_ulaw.sdp
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
#    network_mode: "host"
    depends_on:
      - db
    networks:
      - localnet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    runtime: nvidia
  llm_service:
    image: alejandroqo/llm-service-image
    environment:
      - GROQ_API_KEY=<replaceWithToken>
    #    network_mode: "host"
    ports:
      - "8080:8080"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
